--liquibase formatted sql

--changeset codex:005-create-editorial-catalog-foundations
CREATE TABLE publishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    country VARCHAR(2),
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_publishers_record_status
        CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE catalog_franchises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    description TEXT,
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT chk_catalog_franchises_record_status
        CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE catalog_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    franchise_id BIGINT,
    primary_publisher_id BIGINT,
    title VARCHAR(240) NOT NULL,
    original_title VARCHAR(240),
    type VARCHAR(30) NOT NULL,
    publication_status VARCHAR(30) NOT NULL,
    description TEXT,
    origin_country VARCHAR(2),
    original_language VARCHAR(10),
    start_year INTEGER,
    end_year INTEGER,
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_catalog_series_franchise
        FOREIGN KEY (franchise_id) REFERENCES catalog_franchises (id),
    CONSTRAINT fk_catalog_series_primary_publisher
        FOREIGN KEY (primary_publisher_id) REFERENCES publishers (id),
    CONSTRAINT chk_catalog_series_type
        CHECK (type IN ('BOOK', 'COMIC', 'MANGA')),
    CONSTRAINT chk_catalog_series_publication_status
        CHECK (publication_status IN ('ONGOING', 'COMPLETED', 'CANCELLED', 'HIATUS', 'UNKNOWN')),
    CONSTRAINT chk_catalog_series_record_status
        CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_catalog_series_start_year
        CHECK (start_year IS NULL OR start_year BETWEEN 1000 AND 3000),
    CONSTRAINT chk_catalog_series_end_year
        CHECK (end_year IS NULL OR end_year BETWEEN 1000 AND 3000),
    CONSTRAINT chk_catalog_series_year_range
        CHECK (start_year IS NULL OR end_year IS NULL OR end_year >= start_year)
);

CREATE INDEX idx_publishers_name ON publishers (LOWER(name));
CREATE INDEX idx_publishers_record_status ON publishers (record_status);

CREATE INDEX idx_catalog_franchises_name ON catalog_franchises (LOWER(name));
CREATE INDEX idx_catalog_franchises_slug ON catalog_franchises (slug);
CREATE UNIQUE INDEX uk_catalog_franchises_slug_active
    ON catalog_franchises (slug)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_catalog_franchises_record_status ON catalog_franchises (record_status);

CREATE INDEX idx_catalog_series_franchise_id ON catalog_series (franchise_id);
CREATE INDEX idx_catalog_series_primary_publisher_id ON catalog_series (primary_publisher_id);
CREATE INDEX idx_catalog_series_type ON catalog_series (type);
CREATE INDEX idx_catalog_series_publication_status ON catalog_series (publication_status);
CREATE INDEX idx_catalog_series_record_status ON catalog_series (record_status);
CREATE INDEX idx_catalog_series_title ON catalog_series (LOWER(title));

--rollback DROP TABLE IF EXISTS catalog_series, catalog_franchises, publishers CASCADE;
