--liquibase formatted sql

--changeset codex:006-create-editorial-catalog-items-and-editions
CREATE TABLE catalog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    original_title VARCHAR(240),
    sequence_label VARCHAR(50),
    sort_order NUMERIC(10,3),
    description TEXT,
    first_publication_date DATE,
    first_publication_year INTEGER,
    original_language VARCHAR(10),
    origin_country VARCHAR(2),
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_catalog_items_series
        FOREIGN KEY (series_id) REFERENCES catalog_series (id),
    CONSTRAINT chk_catalog_items_sort_order
        CHECK (sort_order IS NULL OR sort_order >= 0),
    CONSTRAINT chk_catalog_items_first_publication_year
        CHECK (first_publication_year IS NULL OR first_publication_year BETWEEN 1000 AND 3000),
    CONSTRAINT chk_catalog_items_record_status
        CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE catalog_item_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_item_id BIGINT NOT NULL,
    publisher_id BIGINT,
    isbn VARCHAR(32),
    ean VARCHAR(32),
    format VARCHAR(40) NOT NULL,
    edition_name VARCHAR(240),
    publication_date DATE,
    publication_year INTEGER,
    language VARCHAR(10),
    country VARCHAR(2),
    page_count INTEGER,
    cover_image_url VARCHAR(1000),
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_catalog_item_editions_item
        FOREIGN KEY (catalog_item_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_catalog_item_editions_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers (id),
    CONSTRAINT chk_catalog_item_editions_format
        CHECK (format IN ('HARDCOVER', 'PAPERBACK', 'SOFTCOVER', 'DIGITAL', 'OMNIBUS', 'BOX_SET', 'SINGLE_ISSUE', 'OTHER')),
    CONSTRAINT chk_catalog_item_editions_page_count
        CHECK (page_count IS NULL OR page_count > 0),
    CONSTRAINT chk_catalog_item_editions_publication_year
        CHECK (publication_year IS NULL OR publication_year BETWEEN 1000 AND 3000),
    CONSTRAINT chk_catalog_item_editions_record_status
        CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_catalog_items_series_id ON catalog_items (series_id);
CREATE INDEX idx_catalog_items_record_status ON catalog_items (record_status);
CREATE INDEX idx_catalog_items_title ON catalog_items (LOWER(title));
CREATE INDEX idx_catalog_items_sort_order ON catalog_items (sort_order);
CREATE INDEX idx_catalog_items_first_publication_year ON catalog_items (first_publication_year);
CREATE INDEX idx_catalog_items_original_language ON catalog_items (original_language);
CREATE INDEX idx_catalog_items_origin_country ON catalog_items (origin_country);

CREATE INDEX idx_catalog_item_editions_catalog_item_id ON catalog_item_editions (catalog_item_id);
CREATE INDEX idx_catalog_item_editions_publisher_id ON catalog_item_editions (publisher_id);
CREATE INDEX idx_catalog_item_editions_record_status ON catalog_item_editions (record_status);
CREATE UNIQUE INDEX uk_catalog_item_editions_isbn_active
    ON catalog_item_editions (isbn)
    WHERE isbn IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_catalog_item_editions_ean_active
    ON catalog_item_editions (ean)
    WHERE ean IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_catalog_item_editions_format ON catalog_item_editions (format);
CREATE INDEX idx_catalog_item_editions_language ON catalog_item_editions (language);
CREATE INDEX idx_catalog_item_editions_country ON catalog_item_editions (country);
CREATE INDEX idx_catalog_item_editions_publication_year ON catalog_item_editions (publication_year);

--rollback DROP TABLE IF EXISTS catalog_item_editions, catalog_items CASCADE;
