--liquibase formatted sql

--changeset codex:007-create-master-product-catalog-links
CREATE TABLE master_product_catalog_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_product_id BIGINT NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    catalog_item_edition_id BIGINT,
    link_status VARCHAR(30) NOT NULL DEFAULT 'PROPOSED',
    link_source VARCHAR(40) NOT NULL DEFAULT 'MANUAL',
    confidence_score NUMERIC(5,4),
    match_reason TEXT,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_master_product_catalog_links_master_product
        FOREIGN KEY (master_product_id) REFERENCES master_products (id),
    CONSTRAINT fk_master_product_catalog_links_catalog_item
        FOREIGN KEY (catalog_item_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_master_product_catalog_links_catalog_item_edition
        FOREIGN KEY (catalog_item_edition_id) REFERENCES catalog_item_editions (id),
    CONSTRAINT chk_master_product_catalog_links_status
        CHECK (link_status IN ('PROPOSED', 'VERIFIED', 'REJECTED')),
    CONSTRAINT chk_master_product_catalog_links_source
        CHECK (link_source IN ('MANUAL', 'ISBN', 'EAN', 'TITLE', 'TITLE_AND_VOLUME', 'TITLE_AND_PUBLISHER', 'BACKFILL')),
    CONSTRAINT chk_master_product_catalog_links_confidence
        CHECK (confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1)
);

CREATE INDEX idx_master_product_catalog_links_master_product_id
    ON master_product_catalog_links (master_product_id);
CREATE INDEX idx_master_product_catalog_links_catalog_item_id
    ON master_product_catalog_links (catalog_item_id);
CREATE INDEX idx_master_product_catalog_links_catalog_item_edition_id
    ON master_product_catalog_links (catalog_item_edition_id);
CREATE INDEX idx_master_product_catalog_links_status
    ON master_product_catalog_links (link_status);
CREATE INDEX idx_master_product_catalog_links_source
    ON master_product_catalog_links (link_source);
CREATE INDEX idx_master_product_catalog_links_confidence
    ON master_product_catalog_links (confidence_score);
CREATE UNIQUE INDEX uk_master_product_catalog_links_verified_master
    ON master_product_catalog_links (master_product_id)
    WHERE link_status = 'VERIFIED' AND deleted_at IS NULL;

--rollback DROP TABLE IF EXISTS master_product_catalog_links CASCADE;
