--liquibase formatted sql

--changeset codex:011-create-catalog-item-relationships
CREATE TABLE catalog_item_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_catalog_item_id BIGINT NOT NULL,
    target_catalog_item_id BIGINT NOT NULL,
    relationship_type VARCHAR(40) NOT NULL,
    relationship_order INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    record_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    CONSTRAINT fk_catalog_item_relationships_source FOREIGN KEY (source_catalog_item_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_catalog_item_relationships_target FOREIGN KEY (target_catalog_item_id) REFERENCES catalog_items (id),
    CONSTRAINT chk_catalog_item_relationships_distinct_items CHECK (source_catalog_item_id <> target_catalog_item_id),
    CONSTRAINT chk_catalog_item_relationships_order CHECK (relationship_order > 0),
    CONSTRAINT chk_catalog_item_relationships_status CHECK (record_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_catalog_item_relationships_type CHECK (relationship_type IN (
        'ADAPTATION','REMAKE','REPRINT','SAME_WORK','SPIN_OFF','PREQUEL','SEQUEL','RELATED'
    ))
);

CREATE INDEX idx_catalog_item_relationships_source ON catalog_item_relationships (source_catalog_item_id);
CREATE INDEX idx_catalog_item_relationships_target ON catalog_item_relationships (target_catalog_item_id);
CREATE INDEX idx_catalog_item_relationships_type ON catalog_item_relationships (relationship_type);
CREATE INDEX idx_catalog_item_relationships_status ON catalog_item_relationships (record_status);
CREATE INDEX idx_catalog_item_relationships_order ON catalog_item_relationships (relationship_order);
CREATE UNIQUE INDEX uk_catalog_item_relationships_active
    ON catalog_item_relationships (source_catalog_item_id, target_catalog_item_id, relationship_type)
    WHERE deleted_at IS NULL;

--rollback DROP TABLE IF EXISTS catalog_item_relationships CASCADE;
