package com.collectohub.recommendations.dto;

import java.math.BigDecimal;

public record RecommendedShopProductResponse(
        Long shopProductId,
        Long shopId,
        String shopName,
        Long masterProductId,
        String productName,
        String categoryCode,
        String franchise,
        String collectionName,
        String volumeNumber,
        String coverImageUrl,
        Long catalogItemId,
        String catalogItemTitle,
        String catalogItemSequenceLabel,
        Long catalogSeriesId,
        String catalogSeriesTitle,
        Long catalogItemEditionId,
        String catalogItemEditionName,
        String catalogItemEditionFormat,
        String catalogItemEditionIsbn,
        String catalogItemEditionEan,
        String catalogItemEditionCoverImageUrl,
        String catalogPublisherName,
        String catalogFranchiseName,
        String editorialReferenceSource,
        String matchType,
        BigDecimal priceAmount,
        String currency,
        Integer stockQuantity,
        String physicalCondition,
        String commercialStatus,
        RecommendationReasonResponse recommendationReason,
        Long matchedCollectionId,
        String matchedCollectionName,
        String matchedCollectionItemStatus
) {
    public RecommendedShopProductResponse(
            Long shopProductId,
            Long shopId,
            String shopName,
            Long masterProductId,
            String productName,
            String categoryCode,
            String franchise,
            String collectionName,
            String volumeNumber,
            String coverImageUrl,
            BigDecimal priceAmount,
            String currency,
            Integer stockQuantity,
            String physicalCondition,
            String commercialStatus,
            RecommendationReasonResponse recommendationReason,
            Long matchedCollectionId,
            String matchedCollectionName,
            String matchedCollectionItemStatus
    ) {
        this(shopProductId, shopId, shopName, masterProductId, productName, categoryCode,
                franchise, collectionName, volumeNumber, coverImageUrl,
                null, null, null, null, null, null, null, null, null, null, null,
                null, null, "LEGACY", "LEGACY_MASTER_PRODUCT",
                priceAmount, currency, stockQuantity, physicalCondition, commercialStatus,
                recommendationReason, matchedCollectionId, matchedCollectionName,
                matchedCollectionItemStatus);
    }
}
