spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:collectohub}
    username: ${POSTGRES_USER:collectohub}
    password: ${POSTGRES_PASSWORD:collectohub_local_password}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

logging:
  level:
    liquibase: info
